adzuna:
  app_id: "236d479f"
  app_key: "a6f754fed8dab51efc16e990521e23fa"
  country: "us"
  search_term: "python developer"
  location: "remote"
  results_per_page: 5

gemini:
  api_key: "AIzaSyBs35-7UfPxDwfErOhiUt13hkaPwmWZyik"

email:
  smtp_user: "aburagohain10@gmail.com"
  smtp_password: "avol qtom iscs unyi"
  recipient: "abgohain77@gmail.com"
  subject: "🧠 Daily AI Job Digest"
