name: Daily Job Finder

on:
  schedule:
    - cron: '0 6 * * *'   # runs every day at 6 AM UTC
  workflow_dispatch:      # also allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
        ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        EMAIL_SUBJECT: ${{ secrets.EMAIL_SUBJECT }}
      run: python daily_job_finder.py
