name: Debug Schedule Trigger

on:
  schedule:
    - cron: '*/5 * * * *'   # Runs every 5 minutes

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Scheduled workflow triggered at $(date)"
