name: Daily Job Finder

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: '0 7 * * *'   # daily at 7am UTC

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily_job_finder.py
        working-directory: ./        # root folder (JobScout/)
        run: |
          set -x
          python daily_job_finder.py
