name: Daily Job Finder

# Trigger daily job finder at 16:01 UTC
on:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily job finder
      env:
        ADZUNA_APP_ID: ${{ secrets.ADZUNA_APP_ID }}
        ADZUNA_APP_KEY: ${{ secrets.ADZUNA_APP_KEY }}
        ADZUNA_COUNTRY: ${{ secrets.ADZUNA_COUNTRY }}
        ADZUNA_SEARCH_TERM: ${{ secrets.ADZUNA_SEARCH_TERM }}
        ADZUNA_RESULTS_PER_PAGE: ${{ secrets.ADZUNA_RESULTS_PER_PAGE }}

        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

        EMAIL_SMTP_USER: ${{ secrets.EMAIL_SMTP_USER }}
        EMAIL_SMTP_PASSWORD: ${{ secrets.EMAIL_SMTP_PASSWORD }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        EMAIL_SUBJECT: ${{ secrets.EMAIL_SUBJECT }}
      run: python daily_job_finder.py
