name: Debug Daily Job Finder

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: List files in repo
        run: ls -alh

      - name: Show Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "No requirements.txt found"; fi

      - name: Run daily_job_finder.py
        run: python daily_job_finder.py
